# Generated by Django 2.2.3 on 2019-08-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('auditid', models.BigAutoField(db_column='AuditID', primary_key=True, serialize=False)),
                ('tableid', models.SmallIntegerField(db_column='TableID')),
                ('actionid', models.SmallIntegerField(db_column='ActionID')),
                ('rowdata', models.TextField(db_column='RowData')),
                ('chain', models.CharField(db_column='Chain', max_length=32)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'Audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=32)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('creditid', models.BigAutoField(db_column='CreditID', primary_key=True, serialize=False)),
                ('buyerid', models.IntegerField(db_column='BuyerID')),
                ('fromwarehouseid', models.IntegerField(blank=True, db_column='FromWarehouseID', null=True)),
                ('created', models.DateTimeField(db_column='Created')),
                ('towarehouseid', models.IntegerField(blank=True, db_column='ToWarehouseID', null=True)),
                ('sent', models.DateTimeField(blank=True, db_column='Sent', null=True)),
                ('received', models.DateTimeField(blank=True, db_column='Received', null=True)),
            ],
            options={
                'db_table': 'Credit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditcomment',
            fields=[
                ('creditcommentid', models.BigAutoField(db_column='CreditCommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'CreditComment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditdetails',
            fields=[
                ('creditdetailsid', models.BigAutoField(db_column='CreditDetailsID', primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(db_column='Qty', decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'CreditDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditloss',
            fields=[
                ('creditlossid', models.AutoField(db_column='CreditLossID', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'CreditLoss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credittype',
            fields=[
                ('credittypeid', models.AutoField(db_column='CreditTypeID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=32)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=64, null=True)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'CreditType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('debitid', models.BigAutoField(db_column='DebitID', primary_key=True, serialize=False)),
                ('qty', models.DecimalField(db_column='Qty', decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('tracknumber', models.CharField(db_column='TrackNumber', max_length=64, unique=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'Debit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discountid', models.AutoField(db_column='DiscountID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=48)),
                ('value', models.DecimalField(db_column='Value', decimal_places=2, max_digits=10)),
                ('units', models.CharField(db_column='Units', max_length=5)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'Discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Losstype',
            fields=[
                ('losstypeid', models.AutoField(db_column='LossTypeID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=64)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'LossType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetype',
            fields=[
                ('pricetypeid', models.AutoField(db_column='PriceTypeID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=48)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=48, null=True)),
                ('ratio', models.DecimalField(db_column='Ratio', decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'PriceType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.BigAutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=48)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productcomment',
            fields=[
                ('productcommentid', models.BigAutoField(db_column='ProductCommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'ProductComment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=48)),
                ('value', models.CharField(db_column='Value', max_length=32)),
                ('created', models.DateTimeField(db_column='Created')),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseid', models.AutoField(db_column='WarehouseID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=48)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=256, null=True)),
                ('active', models.BooleanField(db_column='Active')),
                ('created', models.DateTimeField(db_column='Created')),
                ('in_field', models.BooleanField(db_column='In')),
                ('out', models.BooleanField(db_column='Out')),
            ],
            options={
                'db_table': 'Warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('productdetailsid', models.BigAutoField(db_column='ProductDetailsID', primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=128, null=True)),
                ('url', models.CharField(blank=True, db_column='Url', max_length=1024, null=True)),
                ('serialno', models.CharField(blank=True, db_column='SerialNo', max_length=128, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, db_column='Height', decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, db_column='Width', decimal_places=2, max_digits=10, null=True)),
                ('lenght', models.DecimalField(blank=True, db_column='Lenght', decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(db_column='Created')),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Product')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.AuthUser')),
            ],
            options={
                'db_table': 'ProductDetails',
                'managed': True,
            },
        ),
    ]
