# Generated by Django 2.2.3 on 2019-08-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'managed': True},
        ),
    ]
