# Generated by Django 2.2.3 on 2019-08-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0002_auto_20190816_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='creditloss',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='debit',
            options={'managed': False, 'ordering': ['-debitid']},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'managed': True, 'ordering': ['statusid']},
        ),
        migrations.RemoveField(
            model_name='status',
            name='value',
        ),
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(db_column='Color', default='#000000', max_length=32),
        ),
        migrations.AddField(
            model_name='status',
            name='userid',
            field=models.ForeignKey(db_column='UserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.AuthUser'),
        ),
    ]
