# Generated by Django 2.2.3 on 2019-08-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0003_auto_20190821_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditloss',
            name='value',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='value',
        ),
        migrations.AddField(
            model_name='credit',
            name='credittypeid',
            field=models.ForeignKey(db_column='CreditTypeID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Credittype'),
        ),
        migrations.AddField(
            model_name='credit',
            name='tracknumber',
            field=models.CharField(blank=True, db_column='TrackNumber', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='userid',
            field=models.ForeignKey(db_column='UserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.AuthUser'),
        ),
        migrations.AddField(
            model_name='creditloss',
            name='creditid',
            field=models.ForeignKey(db_column='CreditID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Credit'),
        ),
        migrations.AddField(
            model_name='creditloss',
            name='losstypeid',
            field=models.ForeignKey(db_column='LossTypeID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Losstype'),
        ),
        migrations.AddField(
            model_name='creditloss',
            name='notes',
            field=models.CharField(blank=True, db_column='Notes', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='creditloss',
            name='rate',
            field=models.DecimalField(db_column='Rate', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditloss',
            name='userid',
            field=models.ForeignKey(db_column='UserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.AuthUser'),
        ),
        migrations.AddField(
            model_name='discount',
            name='rate',
            field=models.DecimalField(db_column='Rate', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='userid',
            field=models.ForeignKey(db_column='UserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.AuthUser'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(db_column='Color', default='000000', max_length=32),
        ),
    ]
