# Generated by Django 2.2.3 on 2019-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0004_auto_20190821_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditloss',
            name='notes2',
            field=models.CharField(blank=True, db_column='Notes2', max_length=1024, null=True),
        ),
    ]
