# Generated by Django 2.2.3 on 2019-08-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0005_creditloss_notes2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditloss',
            name='notes2',
        ),
    ]
