# Generated by Django 2.2.3 on 2019-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0009_remove_creditloss_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditloss',
            name='notes',
            field=models.CharField(blank=True, db_column='Notes', max_length=1024, null=True),
        ),
    ]
