# Generated by Django 2.2.3 on 2019-09-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0010_creditloss_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'managed': True, 'ordering': ['-creditid']},
        ),
        migrations.AlterModelOptions(
            name='creditdetails',
            options={'managed': True},
        ),
    ]
