# Generated by Django 2.2.3 on 2019-09-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0011_auto_20190903_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdetails',
            name='creditid',
            field=models.ForeignKey(db_column='CreditID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Credit'),
        ),
        migrations.AddField(
            model_name='creditdetails',
            name='debitid',
            field=models.ForeignKey(db_column='DebitID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Debit'),
        ),
        migrations.AddField(
            model_name='creditdetails',
            name='pricetypeid',
            field=models.ForeignKey(db_column='PriceTypeID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Pricetype'),
        ),
        migrations.AddField(
            model_name='creditdetails',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Product'),
        ),
        migrations.AddField(
            model_name='creditdetails',
            name='userid',
            field=models.ForeignKey(db_column='UserID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.AuthUser'),
        ),
    ]
