# Generated by Django 2.2.3 on 2019-09-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0012_auto_20190903_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdetails',
            name='debitid',
        ),
    ]
