# Generated by Django 2.2.3 on 2019-09-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0014_creditdetails_debitid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdetails',
            name='debitid',
            field=models.ForeignKey(db_column='DebitID', default=44, on_delete=django.db.models.deletion.DO_NOTHING, to='tradeTools.Debit'),
        ),
    ]
