# Generated by Django 2.2.3 on 2019-09-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTools', '0015_auto_20190903_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='creditcomment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='credittype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='debit',
            options={'managed': True, 'ordering': ['-debitid']},
        ),
        migrations.AlterModelOptions(
            name='losstype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pricetype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'managed': True},
        ),
    ]
